// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gaussian_kernel
arma::mat gaussian_kernel(const arma::mat& coordinates, double bandwidth, Rcpp::Nullable<Rcpp::NumericMatrix> landmarks);
RcppExport SEXP _ssdr_gaussian_kernel(SEXP coordinatesSEXP, SEXP bandwidthSEXP, SEXP landmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coordinates(coordinatesSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type landmarks(landmarksSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel(coordinates, bandwidth, landmarks));
    return rcpp_result_gen;
END_RCPP
}
// ssdr_f_optimize_cpp
Rcpp::List ssdr_f_optimize_cpp(const arma::mat& X, const arma::vec& Sigma_svd, const arma::mat& V_svd, const arma::mat& K, double lambda, int max_iter, double tol);
RcppExport SEXP _ssdr_ssdr_f_optimize_cpp(SEXP XSEXP, SEXP Sigma_svdSEXP, SEXP V_svdSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Sigma_svd(Sigma_svdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_svd(V_svdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ssdr_f_optimize_cpp(X, Sigma_svd, V_svd, K, lambda, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// truncated_svd
Rcpp::List truncated_svd(const arma::mat& X, int rank);
RcppExport SEXP _ssdr_truncated_svd(SEXP XSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_svd(X, rank));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ssdr_gaussian_kernel", (DL_FUNC) &_ssdr_gaussian_kernel, 3},
    {"_ssdr_ssdr_f_optimize_cpp", (DL_FUNC) &_ssdr_ssdr_f_optimize_cpp, 7},
    {"_ssdr_truncated_svd", (DL_FUNC) &_ssdr_truncated_svd, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssdr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
