# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_kernel <- function(coordinates, bandwidth, landmarks = NULL) {
    .Call(`_ssdr_gaussian_kernel`, coordinates, bandwidth, landmarks)
}

ssdr_f_optimize_cpp <- function(X, Sigma_svd, V_svd, K, lambda, max_iter = 100L, tol = 1e-2) {
    .Call(`_ssdr_ssdr_f_optimize_cpp`, X, Sigma_svd, V_svd, K, lambda, max_iter, tol)
}

truncated_svd <- function(X, rank) {
    .Call(`_ssdr_truncated_svd`, X, rank)
}

