#' Spatially Smoothed Dimension Reduction with Neural Poisson Loss (SSDr-NN)
#'
#' Fits the neural Poisson formulation of SSDr. The embedding is generated by a
#' coordinate-driven multilayer perceptron and penalized for spatial roughness
#' using a row-normalized Gaussian neighbor graph.
#'
#' @param X Non-negative numeric count matrix with spots or cells in rows and
#'   genes or features in columns.
#' @param coords Numeric matrix or data frame of spatial coordinates aligned
#'   with the rows of `X`.
#' @param rank Positive integer. Target embedding dimension.
#' @param bandwidth Positive numeric. Gaussian neighbor bandwidth after
#'   column-wise min-max normalization of `coords`.
#' @param lambda Non-negative numeric smoothness weight.
#' @param hidden_dim Positive integer. Width of hidden layers in the coordinate
#'   MLP.
#' @param hidden_layers Non-negative integer. Number of hidden layers in the
#'   coordinate MLP.
#' @param learning_rate Positive numeric. Adam optimizer learning rate.
#' @param max_iter Positive integer. Maximum number of training epochs.
#' @param patience Positive integer. Early-stopping patience.
#' @param tol Non-negative numeric. Minimum relative improvement for resetting
#'   early stopping.
#' @param seed Integer random seed passed to torch.
#'
#' @return An `ssdr_fit` object. The embedding is stored in `fit$U`.
#' @export
#'
#' @examples
#' \dontrun{
#' X <- matrix(rpois(200, lambda = 3), nrow = 20)
#' coords <- cbind(runif(20), runif(20))
#' fit <- ssdr_nn(X, coords, rank = 2, max_iter = 5, patience = 2)
#' dim(fit$U)
#' }
ssdr_nn <- function(X,
                    coords,
                    rank = 5,
                    bandwidth = 0.2,
                    lambda = 1e-2,
                    hidden_dim = 64,
                    hidden_layers = 2,
                    learning_rate = 5e-3,
                    max_iter = 500,
                    patience = 50,
                    tol = 1e-5,
                    seed = 1) {
  call <- match.call()

  old_torch_verify <- Sys.getenv("TORCH_VERIFY_LOAD", unset = NA_character_)
  Sys.setenv(TORCH_VERIFY_LOAD = "FALSE")
  on.exit({
    if (is.na(old_torch_verify)) {
      Sys.unsetenv("TORCH_VERIFY_LOAD")
    } else {
      Sys.setenv(TORCH_VERIFY_LOAD = old_torch_verify)
    }
  }, add = TRUE)
  if (!requireNamespace("torch", quietly = TRUE)) {
    stop("Package `torch` is required for ssdr_nn().", call. = FALSE)
  }
  torch_ready <- isTRUE(tryCatch({
    probe <- torch::torch_tensor(1, dtype = torch::torch_float())
    is.finite(as.numeric(probe$item()))
  }, error = function(e) FALSE))
  if (!torch_ready) {
    stop(
      "The R package `torch` is installed, but its backend is not available. ",
      "Run `torch::install_torch()` and try again.",
      call. = FALSE
    )
  }

  X <- ssdr_as_numeric_matrix(X, "X", nonnegative = TRUE)
  if (missing(coords) || is.null(coords)) stop("`coords` is required.", call. = FALSE)
  coords <- ssdr_normalize_coords(coords)
  if (nrow(X) != nrow(coords)) {
    stop("`nrow(X)` must equal `nrow(coords)`.", call. = FALSE)
  }

  rank <- ssdr_check_rank(rank, X)
  bandwidth <- ssdr_check_scalar(bandwidth, "bandwidth", lower = 0, strict = TRUE)
  lambda <- ssdr_check_scalar(lambda, "lambda", lower = 0)
  hidden_dim <- ssdr_check_integer_scalar(hidden_dim, "hidden_dim")
  hidden_layers <- ssdr_check_integer_scalar(hidden_layers, "hidden_layers", lower = 0)
  learning_rate <- ssdr_check_scalar(learning_rate, "learning_rate", lower = 0, strict = TRUE)
  max_iter <- ssdr_check_integer_scalar(max_iter, "max_iter")
  patience <- ssdr_check_integer_scalar(patience, "patience")
  tol <- ssdr_check_scalar(tol, "tol", lower = 0)
  seed <- as.integer(seed)

  n <- nrow(X)
  p <- ncol(X)
  d <- ncol(coords)

  sqdist <- as.matrix(stats::dist(coords))^2
  W <- exp(-sqdist / (2 * bandwidth^2))
  diag(W) <- 0
  rs <- rowSums(W)
  rs[rs == 0] <- 1
  W <- W / rs

  torch::torch_manual_seed(seed)
  device <- torch::torch_device("cpu")

  x_t <- torch::torch_tensor(X, dtype = torch::torch_float(), device = device)
  coord_t <- torch::torch_tensor(coords, dtype = torch::torch_float(), device = device)
  W_t <- torch::torch_tensor(W, dtype = torch::torch_float(), device = device)

  CoordMLP <- torch::nn_module(
    "CoordMLP",
    initialize = function(input_dim, hidden_dim, output_dim, hidden_layers = 2) {
      self$hidden_layers <- as.integer(hidden_layers)

      if (self$hidden_layers == 0L) {
        self$fc_in <- NULL
        self$fc_hidden <- NULL
        self$fc_out <- torch::nn_linear(input_dim, output_dim)
      } else {
        self$fc_in <- torch::nn_linear(input_dim, hidden_dim)

        if (self$hidden_layers > 1L) {
          self$fc_hidden <- torch::nn_module_list()
          for (i in seq_len(self$hidden_layers - 1L)) {
            self$fc_hidden$append(torch::nn_linear(hidden_dim, hidden_dim))
          }
        } else {
          self$fc_hidden <- NULL
        }

        self$fc_out <- torch::nn_linear(hidden_dim, output_dim)
      }
    },
    forward = function(x) {
      if (self$hidden_layers == 0L) {
        return(self$fc_out(x))
      }

      x <- self$fc_in(x)
      x <- torch::nnf_relu(x)

      if (!is.null(self$fc_hidden)) {
        n_hidden <- length(self$fc_hidden)
        if (n_hidden > 0) {
          for (i in seq_len(n_hidden)) {
            x <- self$fc_hidden[[i]](x)
            x <- torch::nnf_relu(x)
          }
        }
      }

      self$fc_out(x)
    }
  )

  U_net <- CoordMLP(
    input_dim = d,
    hidden_dim = hidden_dim,
    output_dim = rank,
    hidden_layers = hidden_layers
  )
  U_net <- U_net$to(device = device)

  V_param <- torch::nn_parameter(torch::torch_randn(c(p, rank), device = device) * 0.05)
  log_sigma_param <- torch::nn_parameter(torch::torch_zeros(c(rank), device = device))
  b0_param <- torch::nn_parameter(torch::torch_zeros(c(1), device = device))
  alpha_param <- torch::nn_parameter(torch::torch_zeros(c(n, 1), device = device))
  beta_param <- torch::nn_parameter(torch::torch_zeros(c(1, p), device = device))

  params <- c(
    U_net$parameters,
    list(V_param, log_sigma_param, b0_param, alpha_param, beta_param)
  )

  optimizer <- torch::optim_adam(params = params, lr = learning_rate)

  compute_loss <- function() {
    U_raw <- U_net(coord_t)
    U <- U_raw - U_raw$mean(dim = 1, keepdim = TRUE)
    V <- V_param - V_param$mean(dim = 1, keepdim = TRUE)
    sigma_vec <- torch::torch_exp(log_sigma_param)

    low_rank <- torch::torch_matmul(U * sigma_vec$unsqueeze(1), V$t())
    alpha_c <- alpha_param - alpha_param$mean()
    beta_c <- beta_param - beta_param$mean()

    eta <- b0_param + alpha_c + beta_c + low_rank
    mu <- torch::torch_exp(eta)
    nll <- torch::torch_mean(mu - x_t * eta)

    U_norm2 <- torch::torch_sum(U * U, dim = 2, keepdim = TRUE)
    distU <- U_norm2 + U_norm2$t() - 2 * torch::torch_matmul(U, U$t())
    smooth_pen <- torch::torch_sum(W_t * distU) / n
    loss <- nll + lambda * smooth_pen

    list(
      loss = loss,
      nll = nll,
      smooth_pen = smooth_pen,
      U = U,
      V = V,
      sigma = sigma_vec,
      eta = eta,
      mu = mu
    )
  }

  best_loss <- Inf
  best_epoch <- 0
  no_improve <- 0
  loss_trace <- rep(NA_real_, max_iter)
  nll_trace <- rep(NA_real_, max_iter)
  smooth_pen_trace <- rep(NA_real_, max_iter)
  best_snapshot <- NULL

  for (epoch in seq_len(max_iter)) {
    optimizer$zero_grad()

    out <- compute_loss()
    loss <- out$loss
    loss$backward()
    optimizer$step()

    current_loss <- as.numeric(loss$item())
    loss_trace[epoch] <- current_loss
    nll_trace[epoch] <- as.numeric(out$nll$item())
    smooth_pen_trace[epoch] <- as.numeric(out$smooth_pen$item())

    if (is.finite(current_loss) &&
        (!is.finite(best_loss) || current_loss < best_loss - tol * (1 + abs(best_loss)))) {
      best_loss <- current_loss
      best_epoch <- epoch
      no_improve <- 0
      best_snapshot <- list(
        U = as.matrix(out$U$detach()$to(device = "cpu")),
        V = as.matrix(out$V$detach()$to(device = "cpu")),
        sigma = as.numeric(out$sigma$detach()$to(device = "cpu")),
        eta = as.matrix(out$eta$detach()$to(device = "cpu")),
        mu = as.matrix(out$mu$detach()$to(device = "cpu"))
      )
    } else {
      no_improve <- no_improve + 1
    }

    if (no_improve >= patience) {
      break
    }
  }

  if (is.null(best_snapshot)) {
    out <- compute_loss()
    best_snapshot <- list(
      U = as.matrix(out$U$detach()$to(device = "cpu")),
      V = as.matrix(out$V$detach()$to(device = "cpu")),
      sigma = as.numeric(out$sigma$detach()$to(device = "cpu")),
      eta = as.matrix(out$eta$detach()$to(device = "cpu")),
      mu = as.matrix(out$mu$detach()$to(device = "cpu"))
    )
    best_loss <- as.numeric(out$loss$item())
    best_epoch <- max_iter
  }

  U_final <- best_snapshot$U
  V_final <- best_snapshot$V
  sigma_final <- best_snapshot$sigma

  for (k in seq_len(ncol(U_final))) {
    idx_max <- which.max(abs(U_final[, k]))
    if (U_final[idx_max, k] < 0) {
      U_final[, k] <- -U_final[, k]
      V_final[, k] <- -V_final[, k]
    }
  }

  low_rank_final <- U_final %*% diag(sigma_final, nrow = length(sigma_final)) %*% t(V_final)
  diagnostics <- list(
    eta = best_snapshot$eta,
    mu = best_snapshot$mu,
    loss_trace = loss_trace[is.finite(loss_trace)],
    nll_trace = nll_trace[is.finite(nll_trace)],
    smooth_pen_trace = smooth_pen_trace[is.finite(smooth_pen_trace)],
    max_abs_row_mean_lowrank = max(abs(rowMeans(low_rank_final))),
    max_abs_col_mean_lowrank = max(abs(colMeans(low_rank_final))),
    best_epoch = best_epoch
  )

  new_ssdr_fit(
    method = "ssdr_nn",
    U = U_final,
    V = V_final,
    sigma = sigma_final,
    objective = best_loss,
    iterations = length(diagnostics$loss_trace),
    parameters = list(
      rank = rank,
      bandwidth = bandwidth,
      lambda = lambda,
      hidden_dim = hidden_dim,
      hidden_layers = hidden_layers,
      learning_rate = learning_rate,
      max_iter = max_iter,
      patience = patience,
      tol = tol,
      seed = seed
    ),
    diagnostics = diagnostics,
    call = call
  )
}
